Areas/Admin/Controllers/CategorysController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Book.Data;
using Book.IRepository;
using Book.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Book.Unitity;
using Microsoft.AspNetCore.Authorization;

namespace book.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = ManagerRole.Role_Admin)]
    public class CategorysController : Controller
    {
        private readonly ILogger<CategorysController> _logger;
        private readonly IUnitityOfWork _unitityOfWork;

        public CategorysController(ILogger<CategorysController> logger, IUnitityOfWork db)
        {
            _logger = logger;
            _unitityOfWork = db;
        }

        public IActionResult Index()
        {
            List<Categorys> listCategories = _unitityOfWork.Category.GetAll().ToList();
            return View(listCategories);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Categorys obj)
        {
            if(obj.Name == obj.DisplayOrder.ToString())
            {
                ModelState.AddModelError("name", "Tên hiển thị không được trùng với số thứ tự !");
            }
            if(ModelState.IsValid)
            {
              _unitityOfWork.Category.Add(obj);
              _unitityOfWork.Save();
              TempData["success"] = "Bạn đã tạo thành công !";
              return RedirectToAction("Index");
            }
            return View();

        }

        public IActionResult Edit(int? id)
        {
            if(id == null || id==0)
            {
                return NotFound();
            }
            Categorys? categories = _unitityOfWork.Category.Get(p =>p.Id ==id);
            
            if(categories == null)
            {
                return NotFound();
            }
            return View(categories);
        }
        [HttpPost]
        public IActionResult Edit(Categorys obj)
        {
           
            if(ModelState.IsValid)
            {
              _unitityOfWork.Category.Update(obj);
              _unitityOfWork.Save();
              TempData["success"] = "Bạn đã chỉnh sửa thành công !";
              return RedirectToAction("Index");
            }
            return View();

        }

        public IActionResult Delete(int? id)
        {
            if(id == null || id==0)
            {
                return NotFound();
            }
            Categorys? categories = _unitityOfWork.Category.Get(p =>p.Id == id);
            
            if(categories == null)
            {
                return NotFound();
            }
            return View(categories);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePOST(int? id)
        {
            Categorys? foundId = _unitityOfWork.Category.Get(p=> p.Id == id);
            if(foundId == null)
            {
                return NotFound();
            }
            _unitityOfWork.Category.Remove(foundId);
             _unitityOfWork.Save();
             TempData["success"] = "Bạn đã xóa thành công !";
              return RedirectToAction("Index");
           
      
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Areas/Admin/Controllers/ProductsController.cs
using System.Security.AccessControl;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Book.Data;
using Book.IRepository;
using Book.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Book.Unitity;
using Book.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Book.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductsController : Controller
    {
        private readonly ILogger<ProductsController> _logger;
        private readonly IUnitityOfWork _unitityOfWork;

        

        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductsController(ILogger<ProductsController> logger, IUnitityOfWork db,IWebHostEnvironment webHostEnvironment)
        {
            _logger = logger;
            _unitityOfWork = db;
            _webHostEnvironment = webHostEnvironment;
           
        }

        public IActionResult Index()
        {
            List<Products> listProducts = _unitityOfWork.Product.GetAll(includeProperties:"Category").ToList();

            return View(listProducts);
        }

        public IActionResult Upsert(int? id)
        {
          ViewModels productVM = new()
          {
            listCategories = _unitityOfWork.Category.GetAll().Select(
                p => new SelectListItem
                {
                    Text = p.Name,
                    Value = p.Id.ToString()
                }
            ),
            Product = new Products()
          };

          //create
          if(id == null || id == 0)
          {
            return View(productVM);
          }
          //Update
          else
          {
            productVM.Product = _unitityOfWork.Product.Get(p => p.Id == id);
            return View(productVM);
          }
            
            
        }
        [HttpPost]
        public IActionResult Upsert(ViewModels productVM, IFormFile? fileUrl)
        {
         
            if(ModelState.IsValid)
            {
                string pathRoot = _webHostEnvironment.WebRootPath;
              if(fileUrl != null)
               {
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(fileUrl.FileName);
                string productPath = Path.Combine(pathRoot , @"images\product");

                if(!string.IsNullOrEmpty(productVM.Product.ImageUrl))
                {
                    string oldFilePath = Path.Combine(pathRoot, productVM.Product.ImageUrl.TrimStart('\\'));
                    if(System.IO.File.Exists(oldFilePath))
                    {
                        System.IO.File.Delete(oldFilePath);
                    }
                }

                using (var fileStream = new FileStream (Path.Combine(productPath , fileName),FileMode.Create))
                {
                    fileUrl.CopyTo(fileStream);
                };
                productVM.Product.ImageUrl = @"\images\product\" + fileName;
               }


               if(productVM.Product.Id == 0)
               {
                _unitityOfWork.Product.Add(productVM.Product);
               }
               else
               {
                _unitityOfWork.Product.Update(productVM.Product);
               }
              
              _unitityOfWork.Save();
              TempData["success"] = "Bạn đã tạo thành công !";
              return RedirectToAction("Index");
            }
            
            else
            {
       
           productVM.listCategories = _unitityOfWork.Category.GetAll().Select(
                p => new SelectListItem
                {
                    Text = p.Name,
                    Value = p.Id.ToString()
                }
            );

           
            return View(productVM);
          };
            
            

        }




        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }

        #region APICall
        [HttpGet]
        public IActionResult GetAll(int id)
        {
            List<Products> listProducts = _unitityOfWork.Product.GetAll(includeProperties:"Category").ToList();
            return Json( new {Data = listProducts});
        }
        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var productToDelete = _unitityOfWork.Product.Get(p => p.Id == id);
            if(productToDelete == null)
            {
                return Json(new {success = false, message = "Lỗi không thể xóa"});
            }

            var oldFilePath = Path.Combine(_webHostEnvironment.WebRootPath, productToDelete.ImageUrl.TrimStart('\\'));
            if(System.IO.File.Exists(oldFilePath))
            {
                System.IO.File.Delete(oldFilePath);
            }
            _unitityOfWork.Product.Remove(productToDelete);
            _unitityOfWork.Save();
            return Json(new {success=true, message = "Đã xóa thông tin"});

        }
        #endregion



    }

}

Views/Shared/_CartPartial.cshtml
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json
@inject CartService _cartService;


@{
    var cart = _cartService.GetCartItems();
    if (cart.Count > 0) {
        
        <div class="nav-item"><a asp-route="cart">Giỏ hàng(@cart.Count)</a></div>
         
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/Book.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Book</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link "  asp-area="Customer" asp-controller="Home" asp-action="Index">Trang chủ</a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link " asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link " asp-area="Contact" asp-controller="Contact" asp-action="SendContact">Liên hệ</a>
                        </li>
                        @if(User.IsInRole(ManagerRole.Role_Admin)){

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Manager
          </a>
          <ul class="dropdown-menu">
            <li class="nav-item">
                <a class="nav-link text-dark " asp-area="Admin" asp-controller="Categorys" asp-action="Index">Category</a>
            </li>

            <li class="nav-item">
                <a class="nav-link text-dark " asp-area="Admin" asp-controller="Products" asp-action="Index">Product</a>
            </li>     

            <li class="nav-item">
                <a class="nav-link text-dark " asp-area="Contact" asp-controller="Contact" asp-action="Index">Contact</a>
            </li>                 
            <li><hr class="dropdown-divider "></li>

          </ul>
        </li>
                        }
                        
                    </ul>
                    @await Html.PartialAsync("_CartPartial")
                    <partial name="_LoginPartial" ></partial>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification"></partial>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-dark">
        <div class=" text-center ">
         <p> Made with <i class="bi bi-arrow-through-heart-fill"></i> by Hoang Tuan 2023</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    @* <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script> *@
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.tiny.cloud/1/m59ybvw9ksqjymecaudfrg0dr5zdspwkrt4duytwmsa22eii/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
   

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{

    <script src="~/lib/jquery/dist/jquery.min.js" ></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>

}

@if(TempData["Error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js" ></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}